### ISSUE TITLE
App

### ISSUE THREAD

**Issue by xcypher78** [bayazidsustami/nfc-payment#1]
Hello, im testing the app when put track 2 and click emulate the app not responding maybe because your project is on the initial phase correct ?

Thanks

**Comment by bayazidsustami** [comment]
hi, this is incompleted project. you need adjust the aid filter and the apdu command

**Comment by xcypher78** [comment]
> hi, this is incompleted project. you need adjust the aid filter and the apdu command

i dont know how to do

but nice project :) i will be waiting for final release
